### ISSUE TITLE
please relabel libcf build#2 and build#3 to "broken"

### ISSUE THREAD

**Issue by muryanto1** [conda-forge/libcf-feedstock#30]
Hi @conda-forge/core,

Please move libcf build#2 and #3 from ``main`` to ``broken`` on the conda-forge channel on anaconda.org
because we have a list of packages dependent on libcf, and we would like to test the changes that picks up new libnetcdf 4.7.1 locally first, and upload to our own cdat/label/nightly channel, validate all dependent packages. Only after we finish our validation, we will then want to rebuild libcf-feedstock and upload our packages to conda-forge

**Comment by xylar** [comment]
@muryanto1, I think there might be some inconsistency between how CDAT likes to operate and how conda-forge works.  Do you know that those packages are broken or is it just a question of not having tested them yet to your satisfaction?  

If the latter, I would think it would make more sense to just leave them in place, following the conda-forge philosophy of keeping the same pinnings for libnetcdf across all packages, see https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml.  If you need to rebuild or re-release to fix incompatibilities with libnetcdf 4.7.1 later on, the new build or new version would take president over the old.  But marking these builds as broken just because the CDAT team hasn't done sufficient testing seems like it potentially causes more problems than it helps, at least from my perspective.

**Comment by xylar** [comment]
You can recommend to your users to explicitly install libnetcdf 4.6.2 for now if you don't want to pick up the latest version yet.

**Comment by muryanto1** [comment]
I would like to bump the version number instead of just increasing build # for the libnetcdf 4.7.1 and python 38 build..so for now, I would request build#2 and build #3 of  1.0.3 to be relabeled to 'broken'

**Comment by xylar** [comment]
I have requested [gitter](https://gitter.im/conda-forge/conda-forge.github.io) that someone from core take a look.  

In general, I would suggest that the CDAT team come up with a strategy for remaining in sync with the pinnings I linked to above.  One of the things that makes it most difficult for me when I build the E3SM-Unified package including CDAT is that various CDAT packages are pinning versions that aren't consistent with conda-forge.

**Comment by muryanto1** [comment]
@xylar yes, I am working on cdat to build its packages for cdat/label/nightly and cdat/label/v82 using conda-forge-pinning-feedstock/recipe/conda_build_config.yaml.

@mariusvniekerk   Hi! Can you help?
I would like to request libcf 1.0.3 build #2 and build #3 to be labeled as 'broken' in conda-forge.
and then I will submit a PR to get it rebuilt but with a new version 1.0.4.
Is that possible?

I also submitted these issues:
  requested osx-64/libdrs-3.1.2-h5f6846f_5 and linux-64/libdrs-3.1.2-h9abcd1b_5 as "broken" 
  https://github.com/conda-forge/libdrs-feedstock/issues/28

  requested libcdms build#6 to be labeled 'broken'.
  https://github.com/conda-forge/libcdms-feedstock/issues/28

  requested libdrs_f build#5 to be labeled as 'broken' in conda-forge.
  https://github.com/conda-forge/libdrs_f-feedstock/issues/16

**Comment by xylar** [comment]
@mariusvniekerk, I'm sorry to do this but I would ask you to hold off on marking so many packages as broken until I have had a chance to discuss this with @muryanto1 a bit further.  I think there is a misunderstanding about why tests from the CDAT group are failing and what will help.

We are scheduled to talk tomorrow (Friday) and I think time will be saved if we leave things as they are until after that discussion.

**Comment by muryanto1** [comment]
please ignore the request to relabel the pkgs as broken.

**Comment by jakirkham** [comment]
@xylar @muryanto1, could you please summarize the conclusion of your discussion?

**Comment by xylar** [comment]
@jakirkham, I'm happy to.

A number of `conda-forge` packages and several more on the `cdat` channel come together in the `cdat` metapackage.  The CDAT group does nightly testing to see if the `cdat` metapackage is in good working order.

About a week ago, the metapackage started pulling in `libnetcdf=4.7.1` because this was the new pinning on `conda-forge` and the only dependencies that explicitly depended on `libnetcdf` were on `conda-forge`.  However, the tests failed.  The nature of the failure was not very conducive to determining which package had failed or why.

@muryanto1 is pretty new to conda packages in general and to `conda-forge` in particular, having taken over a big project from group members who have moved on to other things.  She was a bit overwhelmed with the broken tests and was only sure that something in the recent rebuilds on `conda-forge` was responsible.  I think it's fair to say that, in a bit of a panic, she asked that the most recent builds be marked as broken until she could figure out the problem.

We had a long phone call and a couple of days of back-and-forth on slack and email.  I suggested that marking a large number of packages as broken without knowing which ones specifically were broken and why wasn't a great approach.  Instead, I suggested that they pin `libnetcdf=4.6.2` in their `cdat` metapackage and work from there.

This was a step in the right direction but it didn't solve all the problems they encountered.  Over the last 2 days, we were able to track down several problems with the feedstocks for several of the packages from the CDAT organization.  These mostly related to not explicitly including dependencies on `libnetcdf` (fixed in https://github.com/conda-forge/libdrs_f-feedstock/pull/17), builds with incorrect, loose `libnetcdf` pinnings, possibly due to incorrect rerendering (fixed in https://github.com/conda-forge/cdtime-feedstock/pull/26, https://github.com/conda-forge/cdtime-feedstock/pull/27, https://github.com/conda-forge/cdms2-feedstock/pull/44 and https://github.com/conda-forge/cdms2-feedstock/pull/42).

We also attempted some other clean-up (e.g. building with `pip` instead of `setuptools`) on various feedstocks with code from CDAT, with varying degrees of success.  Some work remains but my understanding is that things are back up and running without any need to mark any packages as broken.

**Comment by jakirkham** [comment]
Great, thank you for that detailed summary, @xylar! That all makes sense.

Please let us know if there is anything we should be doing to help. Though it sounds like things are getting sorted.
